In [ ]:
Coronavirus timeline:
- January 19: 100 cases
- January 24: 1,000 cases
- February 12: 50,000 cases
- March 6: 100,000 cases
- March 18: 200,000 cases
- March 21: 300,000 cases
- March 24: 400,000 cases
- March 26: 500,000 cases
- March 28: 600,000 cases
- March 29: 700,000 cases
- March 31: 800,000 cases 
- April 1: 900,000 cases
    
    
CoronaVirus in the EAC (Saturday 28th March)

Rwanda - 60

Kenya - 38

Uganda - 30 

Tanzania - 13

Burundi - 0

In [11]:
import numpy as np
import tensorflow as tf

In [10]:
st = "The quick brown fox jumped over the lazy dogs. The dog had 7 bones, right?"

vocab = sorted(set(st.lower())) 

print("Vocab [{}]: {}".format( len(vocab), ", ".join(vocab ) ) )

char2idx = { c:i for i, c in enumerate( vocab ) }
idx2char = np.array( vocab) # indexing follows vocab set order which is sorted asc

print( "\nChar2Idx: {}".format( char2idx ) ) 
print( "\nIdx2Char: {}".format( idx2char ) ) 


Vocab [31]:  , ,, ., 7, ?, a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z

Char2Idx: {' ': 0, ',': 1, '.': 2, '7': 3, '?': 4, 'a': 5, 'b': 6, 'c': 7, 'd': 8, 'e': 9, 'f': 10, 'g': 11, 'h': 12, 'i': 13, 'j': 14, 'k': 15, 'l': 16, 'm': 17, 'n': 18, 'o': 19, 'p': 20, 'q': 21, 'r': 22, 's': 23, 't': 24, 'u': 25, 'v': 26, 'w': 27, 'x': 28, 'y': 29, 'z': 30}

Idx2Char: [' ' ',' '.' '7' '?' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm'
 'n' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [22]:
seq_len = 10
n_per_epoch = len( st ) 

sample_text_as_idx = np.array([ char2idx[c] for c in st.lower() ] ) 

## create training x_txt = y_target pairs as substr(st, i, seq_len) = substr(st, i+1, seq_len+1) 
## such that if seq_len = 3 "Quick" is partitioned as qui = uic, uic = ick, 
char_db = tf.data.Dataset.from_tensor_slices( sample_text_as_idx) 

print( "char_db: {}".format( char_db ) ) 

for i in char_db.take(5):
    print( "{} ==> {}".format( i, idx2char[i.numpy() ] ) )

char_db: <TensorSliceDataset shapes: (), types: tf.int32>
24 ==> t
12 ==> h
9 ==> e
0 ==>  
21 ==> q


In [25]:
## batch method 
seqz = char_db.batch( seq_len+1, drop_remainder=True)
for s in seqz.take(5):
    print( s, " ==> ", repr( '_'.join( idx2char[s.numpy()])))

tf.Tensor([24 12  9  0 21 25 13  7 15  0  6], shape=(11,), dtype=int32)  ==>  't_h_e_ _q_u_i_c_k_ _b'
tf.Tensor([22 19 27 18  0 10 19 28  0 14 25], shape=(11,), dtype=int32)  ==>  'r_o_w_n_ _f_o_x_ _j_u'
tf.Tensor([17 20  9  8  0 19 26  9 22  0 24], shape=(11,), dtype=int32)  ==>  'm_p_e_d_ _o_v_e_r_ _t'
tf.Tensor([12  9  0 16  5 30 29  0  8 19 11], shape=(11,), dtype=int32)  ==>  'h_e_ _l_a_z_y_ _d_o_g'
tf.Tensor([23  2  0 24 12  9  0  8 19 11  0], shape=(11,), dtype=int32)  ==>  's_._ _t_h_e_ _d_o_g_ '


In [38]:
idx2char[ np.array([11:14])+[1, 7]]

SyntaxError: invalid syntax (<ipython-input-38-5371b65eee94>, line 1)